# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: brain.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'brain.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x62rain.proto\x12\x05\x62rain\"h\n\x0cInferRequest\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x11\n\ttimeframe\x18\x02 \x01(\t\x12\x14\n\x0c\x66\x65\x61ture_json\x18\x03 \x01(\t\x12\x0e\n\x06regime\x18\x04 \x01(\t\x12\x0f\n\x07\x63ontext\x18\x05 \x01(\t\"r\n\rInferResponse\x12\x0f\n\x07summary\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\x12\n\nrisk_flags\x18\x03 \x03(\t\x12\x19\n\x11reasoning_bullets\x18\x04 \x03(\t\x12\r\n\x05\x65rror\x18\x05 \x01(\t\"^\n\rCriticRequest\x12\x10\n\x08trade_id\x18\x01 \x01(\t\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12\x15\n\rentry_context\x18\x03 \x01(\t\x12\x14\n\x0coutcome_json\x18\x04 \x01(\t\"]\n\x0e\x43riticResponse\x12\x10\n\x08\x61nalysis\x18\x01 \x01(\t\x12\x0f\n\x07lessons\x18\x02 \x03(\t\x12\x19\n\x11performance_score\x18\x03 \x01(\x02\x12\r\n\x05\x65rror\x18\x04 \x01(\t\"\x1c\n\x0c\x45mbedRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"1\n\rEmbedResponse\x12\x11\n\tembedding\x18\x01 \x03(\x02\x12\r\n\x05\x65rror\x18\x02 \x01(\t2\xc7\x01\n\x0c\x42rainService\x12\x42\n\x15InferCandidateContext\x12\x13.brain.InferRequest\x1a\x14.brain.InferResponse\x12?\n\x10\x43riticPostmortem\x12\x14.brain.CriticRequest\x1a\x15.brain.CriticResponse\x12\x32\n\x05\x45mbed\x12\x13.brain.EmbedRequest\x1a\x14.brain.EmbedResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'brain_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INFERREQUEST']._serialized_start=22
  _globals['_INFERREQUEST']._serialized_end=126
  _globals['_INFERRESPONSE']._serialized_start=128
  _globals['_INFERRESPONSE']._serialized_end=242
  _globals['_CRITICREQUEST']._serialized_start=244
  _globals['_CRITICREQUEST']._serialized_end=338
  _globals['_CRITICRESPONSE']._serialized_start=340
  _globals['_CRITICRESPONSE']._serialized_end=433
  _globals['_EMBEDREQUEST']._serialized_start=435
  _globals['_EMBEDREQUEST']._serialized_end=463
  _globals['_EMBEDRESPONSE']._serialized_start=465
  _globals['_EMBEDRESPONSE']._serialized_end=514
  _globals['_BRAINSERVICE']._serialized_start=517
  _globals['_BRAINSERVICE']._serialized_end=716
# @@protoc_insertion_point(module_scope)
