# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import brain_pb2 as brain__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in brain_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BrainServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InferCandidateContext = channel.unary_unary(
                '/brain.BrainService/InferCandidateContext',
                request_serializer=brain__pb2.InferRequest.SerializeToString,
                response_deserializer=brain__pb2.InferResponse.FromString,
                _registered_method=True)
        self.CriticPostmortem = channel.unary_unary(
                '/brain.BrainService/CriticPostmortem',
                request_serializer=brain__pb2.CriticRequest.SerializeToString,
                response_deserializer=brain__pb2.CriticResponse.FromString,
                _registered_method=True)
        self.Embed = channel.unary_unary(
                '/brain.BrainService/Embed',
                request_serializer=brain__pb2.EmbedRequest.SerializeToString,
                response_deserializer=brain__pb2.EmbedResponse.FromString,
                _registered_method=True)
        self.RunCouncilStage = channel.unary_unary(
                '/brain.BrainService/RunCouncilStage',
                request_serializer=brain__pb2.CouncilStageRequest.SerializeToString,
                response_deserializer=brain__pb2.CouncilStageResponse.FromString,
                _registered_method=True)
        self.ComputeFeatures = channel.unary_unary(
                '/brain.BrainService/ComputeFeatures',
                request_serializer=brain__pb2.FeatureRequest.SerializeToString,
                response_deserializer=brain__pb2.FeatureResponse.FromString,
                _registered_method=True)
        self.ScanUniverse = channel.unary_unary(
                '/brain.BrainService/ScanUniverse',
                request_serializer=brain__pb2.ScanRequest.SerializeToString,
                response_deserializer=brain__pb2.ScanResponse.FromString,
                _registered_method=True)
        self.BatchScore = channel.unary_unary(
                '/brain.BrainService/BatchScore',
                request_serializer=brain__pb2.BatchScoreRequest.SerializeToString,
                response_deserializer=brain__pb2.BatchScoreResponse.FromString,
                _registered_method=True)


class BrainServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def InferCandidateContext(self, request, context):
        """Original RPCs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CriticPostmortem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Embed(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunCouncilStage(self, request, context):
        """Level 3A: Distributed council — PC2 runs perception agents (Stage 1)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ComputeFeatures(self, request, context):
        """Level 3B: Feature computation offload — PC2 computes features via GPU
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ScanUniverse(self, request, context):
        """Level 3C: Discovery scanning — PC2 runs parallel universe scanner
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchScore(self, request, context):
        """Level 2B: Batch ML scoring — PC2 scores multiple symbols via GPU
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BrainServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InferCandidateContext': grpc.unary_unary_rpc_method_handler(
                    servicer.InferCandidateContext,
                    request_deserializer=brain__pb2.InferRequest.FromString,
                    response_serializer=brain__pb2.InferResponse.SerializeToString,
            ),
            'CriticPostmortem': grpc.unary_unary_rpc_method_handler(
                    servicer.CriticPostmortem,
                    request_deserializer=brain__pb2.CriticRequest.FromString,
                    response_serializer=brain__pb2.CriticResponse.SerializeToString,
            ),
            'Embed': grpc.unary_unary_rpc_method_handler(
                    servicer.Embed,
                    request_deserializer=brain__pb2.EmbedRequest.FromString,
                    response_serializer=brain__pb2.EmbedResponse.SerializeToString,
            ),
            'RunCouncilStage': grpc.unary_unary_rpc_method_handler(
                    servicer.RunCouncilStage,
                    request_deserializer=brain__pb2.CouncilStageRequest.FromString,
                    response_serializer=brain__pb2.CouncilStageResponse.SerializeToString,
            ),
            'ComputeFeatures': grpc.unary_unary_rpc_method_handler(
                    servicer.ComputeFeatures,
                    request_deserializer=brain__pb2.FeatureRequest.FromString,
                    response_serializer=brain__pb2.FeatureResponse.SerializeToString,
            ),
            'ScanUniverse': grpc.unary_unary_rpc_method_handler(
                    servicer.ScanUniverse,
                    request_deserializer=brain__pb2.ScanRequest.FromString,
                    response_serializer=brain__pb2.ScanResponse.SerializeToString,
            ),
            'BatchScore': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchScore,
                    request_deserializer=brain__pb2.BatchScoreRequest.FromString,
                    response_serializer=brain__pb2.BatchScoreResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'brain.BrainService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('brain.BrainService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BrainService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InferCandidateContext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/brain.BrainService/InferCandidateContext',
            brain__pb2.InferRequest.SerializeToString,
            brain__pb2.InferResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CriticPostmortem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/brain.BrainService/CriticPostmortem',
            brain__pb2.CriticRequest.SerializeToString,
            brain__pb2.CriticResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Embed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/brain.BrainService/Embed',
            brain__pb2.EmbedRequest.SerializeToString,
            brain__pb2.EmbedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunCouncilStage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/brain.BrainService/RunCouncilStage',
            brain__pb2.CouncilStageRequest.SerializeToString,
            brain__pb2.CouncilStageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ComputeFeatures(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/brain.BrainService/ComputeFeatures',
            brain__pb2.FeatureRequest.SerializeToString,
            brain__pb2.FeatureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ScanUniverse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/brain.BrainService/ScanUniverse',
            brain__pb2.ScanRequest.SerializeToString,
            brain__pb2.ScanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchScore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/brain.BrainService/BatchScore',
            brain__pb2.BatchScoreRequest.SerializeToString,
            brain__pb2.BatchScoreResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
