<#
.SYNOPSIS
    Launch Embodier Trader in development mode (Electron + live backend + Vite HMR).

.DESCRIPTION
    Starts all three processes for local development:
      1. Backend (uvicorn via run_server.py on port 8001)
      2. Frontend (Vite dev server on port 3000)
      3. Electron shell (connects to localhost:3000)

    Role-aware: detects ESPENMAIN vs Profit Trader from hostname.
    Also generates the .bat launcher for Task Scheduler integration.

.PARAMETER BackendOnly
    Only start the backend (no frontend or Electron).

.PARAMETER NoElectron
    Start backend + frontend but skip Electron (browser-only dev).
#>

param(
    [switch]$BackendOnly,
    [switch]$NoElectron
)

$ErrorActionPreference = "Stop"

$ROOT = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
if (-not (Test-Path (Join-Path $ROOT "backend"))) {
    $ROOT = Split-Path -Parent $MyInvocation.MyCommand.Path
}

$BACKEND_DIR = Join-Path $ROOT "backend"
$FRONTEND_DIR = Join-Path $ROOT "frontend-v2"
$DESKTOP_DIR = Join-Path $ROOT "desktop"

$HOSTNAME = $env:COMPUTERNAME
$ROLE = "full"
if ($HOSTNAME -match "ESPENMAIN") { $ROLE = "primary" }
elseif ($HOSTNAME -match "Profit" -or $HOSTNAME -match "PROFITTRADER") { $ROLE = "secondary" }

Write-Host ""
Write-Host "============================================" -ForegroundColor Cyan
Write-Host "  Embodier Trader — Dev Mode Launch" -ForegroundColor Cyan
Write-Host "============================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "  Hostname: $HOSTNAME"
Write-Host "  Role:     $ROLE"
Write-Host "  Backend:  http://localhost:8001"
Write-Host "  Frontend: http://localhost:3000"
Write-Host ""

# ── Generate .bat launcher (for Task Scheduler) ─────────────────────────────

$BAT_PATH = Join-Path $ROOT "scripts" "launch-electron-dev.bat"
$batContent = @"
@echo off
REM Embodier Trader — Dev Mode Auto-Launch (generated by launch-electron-dev.ps1)
REM Role: $ROLE | Host: $HOSTNAME

cd /d "$BACKEND_DIR"
start "Embodier-Backend" cmd /c "call venv\Scripts\activate.bat && python run_server.py"

timeout /t 8 /nobreak >nul

cd /d "$FRONTEND_DIR"
start "Embodier-Frontend" cmd /c "npm run dev"

timeout /t 5 /nobreak >nul

cd /d "$DESKTOP_DIR"
set NODE_ENV=development
start "Embodier-Electron" cmd /c "npx electron ."
"@

Set-Content -Path $BAT_PATH -Value $batContent -Encoding ASCII
Write-Host "  Generated: $BAT_PATH" -ForegroundColor Green
Write-Host ""

# ── Start processes ──────────────────────────────────────────────────────────

# 1. Backend
Write-Host "[1/3] Starting backend..." -ForegroundColor Yellow

$VENV_ACTIVATE = Join-Path $BACKEND_DIR "venv\Scripts\Activate.ps1"
$VENV_PYTHON = Join-Path $BACKEND_DIR "venv\Scripts\python.exe"

if (Test-Path $VENV_PYTHON) {
    $backendJob = Start-Process -FilePath $VENV_PYTHON `
        -ArgumentList "run_server.py" `
        -WorkingDirectory $BACKEND_DIR `
        -PassThru -WindowStyle Normal
    Write-Host "  Backend PID: $($backendJob.Id)" -ForegroundColor Green
} else {
    $backendJob = Start-Process -FilePath "python" `
        -ArgumentList "run_server.py" `
        -WorkingDirectory $BACKEND_DIR `
        -PassThru -WindowStyle Normal
    Write-Host "  Backend PID: $($backendJob.Id) (system python)" -ForegroundColor Yellow
}

if ($BackendOnly) {
    Write-Host ""
    Write-Host "  Backend-only mode. Press Ctrl+C to stop." -ForegroundColor Cyan
    Wait-Process -Id $backendJob.Id
    exit 0
}

# Wait for backend to be ready
Write-Host "  Waiting for backend health..." -ForegroundColor DarkGray
$ready = $false
for ($i = 0; $i -lt 30; $i++) {
    Start-Sleep -Seconds 2
    try {
        $response = Invoke-WebRequest -Uri "http://localhost:8001/healthz" -TimeoutSec 2 -ErrorAction SilentlyContinue
        if ($response.StatusCode -eq 200) {
            $ready = $true
            break
        }
    } catch {}
}

if ($ready) {
    Write-Host "  Backend ready!" -ForegroundColor Green
} else {
    Write-Host "  WARNING: Backend not healthy after 60s, continuing anyway..." -ForegroundColor Yellow
}

# 2. Frontend
Write-Host "[2/3] Starting frontend (Vite)..." -ForegroundColor Yellow

$frontendJob = Start-Process -FilePath "npm" `
    -ArgumentList "run", "dev" `
    -WorkingDirectory $FRONTEND_DIR `
    -PassThru -WindowStyle Normal
Write-Host "  Frontend PID: $($frontendJob.Id)" -ForegroundColor Green

if ($NoElectron) {
    Write-Host ""
    Write-Host "  No-Electron mode. Open http://localhost:3000 in your browser." -ForegroundColor Cyan
    Write-Host "  Press Ctrl+C to stop all processes." -ForegroundColor Cyan
    Write-Host ""
    try {
        Wait-Process -Id $backendJob.Id
    } finally {
        Stop-Process -Id $frontendJob.Id -Force -ErrorAction SilentlyContinue
    }
    exit 0
}

# Wait for Vite to start
Start-Sleep -Seconds 5

# 3. Electron
Write-Host "[3/3] Starting Electron..." -ForegroundColor Yellow

$env:NODE_ENV = "development"
$electronJob = Start-Process -FilePath "npx" `
    -ArgumentList "electron", "." `
    -WorkingDirectory $DESKTOP_DIR `
    -PassThru -WindowStyle Normal
Write-Host "  Electron PID: $($electronJob.Id)" -ForegroundColor Green

Write-Host ""
Write-Host "============================================" -ForegroundColor Green
Write-Host "  All services running!" -ForegroundColor Green
Write-Host "============================================" -ForegroundColor Green
Write-Host ""
Write-Host "  Backend:  http://localhost:8001 (PID $($backendJob.Id))"
Write-Host "  Frontend: http://localhost:3000 (PID $($frontendJob.Id))"
Write-Host "  Electron: PID $($electronJob.Id)"
Write-Host ""
Write-Host "  Close the Electron window or press Ctrl+C to stop all."
Write-Host ""

# Wait for Electron to close, then clean up
try {
    Wait-Process -Id $electronJob.Id -ErrorAction SilentlyContinue
} finally {
    Write-Host ""
    Write-Host "Shutting down..." -ForegroundColor Yellow
    Stop-Process -Id $frontendJob.Id -Force -ErrorAction SilentlyContinue
    Stop-Process -Id $backendJob.Id -Force -ErrorAction SilentlyContinue
    Write-Host "All processes stopped." -ForegroundColor Green
}
